model:
    arch: pspnet
data:
    dataset: mit_sceneparsing_benchmark
    train_split: training
    val_split: validation
    img_rows: 512
    img_cols: 512
    path: /data/CORE3D/AOIS/Dayton_20sqkm/pngdata/
training:
    train_iters: 500000
    batch_size: 4
    val_interval: 100
    n_workers: 16
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: pspnet_dayton_best_model.pkl
